const MIN_PEOPLE_COUNT = 2
const MAX_PEOPLE_COUNT = 10

const MIN_DESCRIPTION_LETTERS = 50
const MAX_DESCRIPTION_LETTERS = 30

export {
  MAX_DESCRIPTION_LETTERS,
  MAX_PEOPLE_COUNT,
  MIN_DESCRIPTION_LETTERS,
  MIN_PEOPLE_COUNT,
};
